In [2]:
import numpy as np

___

# Bài tập 1
- Tạo mảng 1 chiều $x$ gồm n số thực
- Chọn 3 hàm số tuỳ ý $f_1(x)$, $f_2(x)$, $f_3(x)$. Tạo 3 mảng bằng cách truyền $x$ vào trong 3 hàm số.
- Ghép bốn mảng một chiều thành một mảng hai chiều kích thước $n\times4$

In [3]:
n = 10
arr1 = np.arange(n)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# Khởi tạo 3 hàm số

def f1_x(arr):
    return arr * 2

def f2_x(arr):
    return arr ** 2

def f3_x(arr):
    return arr / 2

In [5]:
arr2 = f1_x(arr1)
arr3 = f2_x(arr1)
arr4 = f3_x(arr1)

print(f"Hàm số f1(x) = {arr2}")
print(f"Hàm số f1(x) = {arr3}")
print(f"Hàm số f1(x) = {arr4}")

Hàm số f1(x) = [ 0  2  4  6  8 10 12 14 16 18]
Hàm số f1(x) = [ 0  1  4  9 16 25 36 49 64 81]
Hàm số f1(x) = [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [6]:
# Ghép 4 mảng một chiều thành một mảng 2 chiều kích thước nx4

arr2d = np.vstack([arr1, arr2, arr3, arr4])
arr2d.T

array([[ 0. ,  0. ,  0. ,  0. ],
       [ 1. ,  2. ,  1. ,  0.5],
       [ 2. ,  4. ,  4. ,  1. ],
       [ 3. ,  6. ,  9. ,  1.5],
       [ 4. ,  8. , 16. ,  2. ],
       [ 5. , 10. , 25. ,  2.5],
       [ 6. , 12. , 36. ,  3. ],
       [ 7. , 14. , 49. ,  3.5],
       [ 8. , 16. , 64. ,  4. ],
       [ 9. , 18. , 81. ,  4.5]])

___

# Bài tập 2
- Tải dữ liệu file `heart_rate.txt` vào trong mảng `a`
- Thực hiện mô tả thống kê với các biến `Time` và `Heart Rate`: Cỡ mẫu, trung bình, trung vị, độ lệch chuẩn, giá trị lớn nhất, nhỏ nhất, phần tư Q1, Q2 và Q3

In [7]:
data = '/home/gudchant/data1-numpy/data1-numpy/excercises/heart_rate.txt'
a = np.loadtxt(data, delimiter=',', skiprows=1)
a

array([[   0.,  103.],
       [   5.,  103.],
       [  10.,  103.],
       [  15.,  105.],
       [  20.,  108.],
       [  25.,  110.],
       [  30.,  110.],
       [  35.,  112.],
       [  40.,  112.],
       [  45.,  114.],
       [  50.,  114.],
       [  55.,  117.],
       [  60.,  117.],
       [  65.,  118.],
       [  70.,  119.],
       [  75.,  119.],
       [  80.,  120.],
       [  85.,  121.],
       [  90.,  121.],
       [  95.,  122.],
       [ 100.,  123.],
       [ 105.,  124.],
       [ 110.,  124.],
       [ 115.,  125.],
       [ 120.,  126.],
       [ 125.,  127.],
       [ 130.,  128.],
       [ 135.,  127.],
       [ 140.,  128.],
       [ 145.,  128.],
       [ 150.,  129.],
       [ 155.,  129.],
       [ 160.,  130.],
       [ 165.,  131.],
       [ 170.,  132.],
       [ 175.,  132.],
       [ 180.,  132.],
       [ 185.,  133.],
       [ 190.,  134.],
       [ 195.,  135.],
       [ 200.,  135.],
       [ 205.,  135.],
       [ 210.,  135.],
       [ 21

In [8]:
a_time = a[:, 0]
a_heart_rate = a[:, 1]

In [9]:
print(f"Cỡ mẫu Time: {np.size(a_time)}")
print(f"Cỡ mẫu Heart Rate: {np.size(a_heart_rate)}")

Cỡ mẫu Time: 241
Cỡ mẫu Heart Rate: 241


In [10]:
print(f"Trung bình Time: {np.mean(a_time)}")
print(f"Trung bình Heart Rate: {np.mean(a_heart_rate)}")

Trung bình Time: 600.0
Trung bình Heart Rate: 142.98340248962654


In [11]:
print(f"Trung vị Time: {np.median(a_time)}")
print(f"Trung vị Heart Rate: {np.median(a_heart_rate)}")

Trung vị Time: 600.0
Trung vị Heart Rate: 147.0


In [12]:
print(f"Độ lệch chuẩn Time: {np.std(a_time)}")
print(f"Độ lệch chuẩn Heart Rate: {np.std(a_heart_rate)}")

Độ lệch chuẩn Time: 347.85054261852173
Độ lệch chuẩn Heart Rate: 11.36346581057221


In [13]:
print(f"Giá trị lớn nhất Time: {np.max(a_time)}")
print(f"Giá trị lớn nhât Heart Rate: {np.max(a_heart_rate)}")

Giá trị lớn nhất Time: 1200.0
Giá trị lớn nhât Heart Rate: 154.0


In [14]:
print(f"Giá trị nhỏ nhât Time: {np.min(a_time)}")
print(f"Giá trị nhỏ nhât Heart Rate: {np.min(a_heart_rate)}")

Giá trị nhỏ nhât Time: 0.0
Giá trị nhỏ nhât Heart Rate: 103.0


In [15]:
print(f"Góc phần tư Q1 Time: {np.percentile(a_time, 25)}")
print(f"Góc phần tư Q1 Heart Rate: {np.percentile(a_heart_rate, 25)}")

Góc phần tư Q1 Time: 300.0
Góc phần tư Q1 Heart Rate: 138.0


In [16]:
print(f"Góc phần tư Q2 Time: {np.percentile(a_time, 50)}")
print(f"Góc phần tư Q2 Heart Rate: {np.percentile(a_heart_rate, 50)}")

Góc phần tư Q2 Time: 600.0
Góc phần tư Q2 Heart Rate: 147.0


In [17]:
print(f"Góc phần tư Q3 Time: {np.percentile(a_time, 75)}")
print(f"Góc phần tư Q3 Heart Rate: {np.percentile(a_heart_rate, 75)}")

Góc phần tư Q3 Time: 900.0
Góc phần tư Q3 Heart Rate: 151.0


___

# Bài tập 3
- Tạo một mảng 2-chiều `a` cỡ $m\times n$
- Các phần tử hàng đầu tiên chạy từ `1` $\longrightarrow$ `n`
- Các phần tử cột đầu tiên nhận giá trị bằng `1`
- Các phần tử cột cuối cùng nhận giá trị bằng `n`
- Các phần tử còn lại tính theo mô tả sau
    ![Phần tử hàng dưới bằng trung bình ba phần tử xung quanh ở hàng trên](/home/gudchant/data1-numpy/data1-numpy/excercises/image.png)

In [18]:
m = 4
n = 4

arr = np.ones((m, n))

for i in range(n):
    arr[0][i] = i+1

for j in range(m):
    arr[j][n-1] = 1
    arr[j][n-1] = n

for a in range(1, m):
    for b in range(1, n-1):
        arr[a][b] = (arr[a-1][b-1] + arr[a-1][b] + arr[a-1][b+1]) / 3

print(arr)


[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


---

# Bài tập 4
Bài tập này sẽ cho các bạn thấy được việc vector hoá quá trình tính toán sẽ tăng tốc độ hiệu quả tới mức nào

Trong bài tập này, các bạn cũng sẽ được giới thiệu với một thuật toán Machine Learning (nhưng các bạn hiện tại chưa cần hiểu nó đang làm gì)

1. Bài tập này gồm 2 file: Một file Jupyter notebook `knn.ipynb` và một file Python `k_nearest_neighbor.py` chứa phần code các bạn sẽ phải implement
2. Trong notebook, biến `num_training` là số phần tử của tập training cho mô hình. Đối với vài tập numpy này, nó là số chiều thứ nhất của ma trận mà các bạn sẽ phải tính toán (property `X_train` của class `KNearestNeighbor`). Chiều còn lại của ma trận này là dữ liệu ảnh đã được "flatten" (biến từ ma trận nhiều chiều thành vector), có kích thước ~3000
3. Biến `num_training` ban đầu được đặt là 2000, nghĩa là chỉ lấy 2000 ảnh cho việc huấn luyện và chỉ tính toán với 2000 vector đối với numpy. Hãy thử implement numpy đối với các hàm được yêu cầu trong class này đối với số luọng dữ liệu này trước.

    Bài tập có yêu cầu các bạn tính toán [khoảng cách L2](https://vi.wikipedia.org/wiki/Kho%E1%BA%A3ng_c%C3%A1ch_Euclid). Các bạn có thể tham khảo thêm về cách tính khoảng cách này [ở đây](https://www.geeksforgeeks.org/calculate-the-euclidean-distance-using-numpy/)

4. Tối ưu hoá: Yêu cầu của bài tập này là thuật toán phải hoạt động hiểu quả với số `num_training` _ít nhất_ là __5000__. Các bạn có thể kiểm tra implementation của mình đối với toàn bộ dữ liệu đã có (50000 ảnh)

    Các bạn có máy tính RAM to có thể không gặp vấn đề gì với 2000 ảnh, nhưng với 5000 ảnh gần như chắc chắc các implementation kiểu "hacker" một dòng sẽ đều gặp phải vấn đề. Mình cũng đã bị dính lỗi như vậy

5. Thời gian: Trong cell code cuối của notebook có phần so sánh thời gian thực hiện thuật toán. Với implementation của mình thì thời gian xử lý 5000 ảnh giảm từ ~1 phút (đối với implementation loop) xuống còn ~0.4s. Từ đây các bạn sẽ thấy được sức mạnh của việc tính toán bằng numpy và xử lý vector hoá.

---

# Extra

In [20]:
a = np.random.randint(1,10000, (2000,1000))
a

array([[2673, 5053, 7481, ..., 1835, 6695, 4447],
       [9305, 2816, 2679, ..., 6094, 4151, 3666],
       [8161,  512, 6611, ..., 5342, 2003, 6621],
       ...,
       [ 573, 4064, 1093, ..., 6270, 1161, 7693],
       [5528, 6136, 5183, ..., 5137, 8784, 2570],
       [8715, 2194, 4117, ..., 6756, 9607, 3229]])

In [21]:
b = np.random.randint(0,999,1000)
b

array([318, 230, 707, 391, 466, 599,  92, 300, 704, 419,  24,   2, 850,
       467, 417, 799, 323, 553, 424, 299, 736, 419, 295, 774, 235, 130,
       785,  29, 815, 431, 684, 358, 913, 414, 321, 487, 126, 795, 317,
        79, 392,  94, 696, 716, 989, 463, 431, 807, 168, 491, 155, 652,
        51,  87, 257, 734, 645, 825, 819, 963, 847, 132, 231, 353, 342,
       353, 387, 824, 638, 245, 634, 643, 651, 183, 808, 466, 809, 639,
       853, 171, 280, 844, 824, 142, 591, 666, 738, 358, 362, 990, 513,
       298, 472, 720, 230, 159,  23, 470, 798, 551, 163, 992, 894, 247,
       332,   8, 633, 833, 129, 477,  74, 849,  74, 469, 807, 905, 513,
       837, 146, 925, 417, 584, 493, 967,  44,  78, 385, 850, 527, 653,
       426, 107, 841, 764, 872, 918, 448, 650, 824, 200, 216, 692, 108,
       571, 276, 726,  20, 481, 256, 538, 198, 625, 177, 701, 588, 191,
       874, 442, 341, 326, 816, 784, 919, 744, 426,  77, 398, 263,  60,
       913, 431, 521, 477, 380, 568, 934,  98, 156, 416, 342, 14

In [22]:
print(b[0])
print(a[0, b[0]])

318
3988


In [23]:
arr = np.zeros(b.shape)

for i in range(arr.shape[0]):
    arr[i] = a[i, b[i]]

arr

array([3.988e+03, 4.857e+03, 4.146e+03, 1.902e+03, 3.163e+03, 8.000e+00,
       6.456e+03, 6.336e+03, 5.320e+02, 7.467e+03, 8.793e+03, 5.779e+03,
       7.417e+03, 9.871e+03, 1.856e+03, 9.951e+03, 4.429e+03, 2.175e+03,
       1.610e+02, 7.947e+03, 6.444e+03, 2.229e+03, 9.187e+03, 7.720e+02,
       8.468e+03, 3.467e+03, 1.458e+03, 6.140e+02, 6.399e+03, 3.319e+03,
       3.550e+03, 3.452e+03, 9.687e+03, 9.555e+03, 8.321e+03, 6.987e+03,
       5.170e+03, 9.008e+03, 4.730e+02, 4.957e+03, 7.612e+03, 5.812e+03,
       9.595e+03, 8.881e+03, 5.007e+03, 3.140e+02, 3.165e+03, 2.051e+03,
       9.240e+03, 9.452e+03, 8.574e+03, 9.482e+03, 4.110e+03, 1.296e+03,
       8.419e+03, 4.208e+03, 8.606e+03, 4.808e+03, 2.886e+03, 4.700e+03,
       2.902e+03, 5.739e+03, 7.913e+03, 1.913e+03, 2.319e+03, 3.070e+03,
       7.759e+03, 7.424e+03, 5.159e+03, 8.211e+03, 3.412e+03, 2.629e+03,
       9.706e+03, 1.456e+03, 9.428e+03, 8.851e+03, 5.714e+03, 9.390e+03,
       8.606e+03, 7.030e+03, 7.462e+03, 7.947e+03, 